### ISSUE TITLE
Incorrect of implementation of export_command for PNG

### ISSUE THREAD

**Issue by TimothyVermeirenBiztory** [tableau/tabcmd#184]
Hi! A user raised a question in an internal Tableau Slack channel about issues when using the `export` command for PNGs. ([Link](https://salesforce-external.slack.com/archives/CA6FMQJ2X/p1665050056650429) in case you have access to said channel.)

They'd attempt something along the lines of `tabcmd export "wb/view" --png -f "output.png`, and see an error saying `'ViewItem' object has no attribute png`.

I've taken a quick look at the Python code and found that [line 147 of export_command.py](https://github.com/tableau/tabcmd/blob/1c7ae58dbbd8537c82522667d3067805c7ed0a07/tabcmd/commands/datasources_and_workbooks/export_command.py#L147) refers to `view_item.png`. However, that's not the right attribute after `populate_image`; it should be `view_item.image`.

As a barely amateur developer, I'm not very well acquainted with how I'd go and pull, then fix this myself (Git flow-wise), so I thought I'd just bring this up as an issue. The fix is trivial, so if you let me know what that process is, happy to follow standard procedure instead.

Cheers!

**Comment by jacalata** [comment]
This is fixed in the latest release - I'll close this now, but feel free to re-open it if there's anything missing or further work needed.

**Comment by lhanik** [comment]
@jacalata: I'm afraid it doesn't work. Moreover, duplicate logging is still present.
![image](https://user-images.githubusercontent.com/116584219/201405423-cdf06188-bca9-4a3f-b1b6-6d8122e7194f.png)

**Comment by lhanik** [comment]
@jacalata thanks for prompt response; it works now
![image](https://user-images.githubusercontent.com/116584219/202799687-d50e0b3b-1dd7-4f33-a78f-1a797ea48b09.png)
